# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /var/lib/snapd/snap/clion/151/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /var/lib/snapd/snap/clion/151/bin/cmake/linux/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bitterboyy/Documents/chameleon-chess

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bitterboyy/Documents/chameleon-chess

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/var/lib/snapd/snap/clion/151/bin/cmake/linux/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/var/lib/snapd/snap/clion/151/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bitterboyy/Documents/chameleon-chess/CMakeFiles /home/bitterboyy/Documents/chameleon-chess//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bitterboyy/Documents/chameleon-chess/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named chameleon

# Build rule for target.
chameleon: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chameleon
.PHONY : chameleon

# fast build rule for target.
chameleon/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chameleon.dir/build.make CMakeFiles/chameleon.dir/build
.PHONY : chameleon/fast

ChessEngine/debug.o: ChessEngine/debug.cpp.o

.PHONY : ChessEngine/debug.o

# target to build an object file
ChessEngine/debug.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chameleon.dir/build.make CMakeFiles/chameleon.dir/ChessEngine/debug.cpp.o
.PHONY : ChessEngine/debug.cpp.o

ChessEngine/debug.i: ChessEngine/debug.cpp.i

.PHONY : ChessEngine/debug.i

# target to preprocess a source file
ChessEngine/debug.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chameleon.dir/build.make CMakeFiles/chameleon.dir/ChessEngine/debug.cpp.i
.PHONY : ChessEngine/debug.cpp.i

ChessEngine/debug.s: ChessEngine/debug.cpp.s

.PHONY : ChessEngine/debug.s

# target to generate assembly for a file
ChessEngine/debug.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chameleon.dir/build.make CMakeFiles/chameleon.dir/ChessEngine/debug.cpp.s
.PHONY : ChessEngine/debug.cpp.s

ChessEngine/display.o: ChessEngine/display.cpp.o

.PHONY : ChessEngine/display.o

# target to build an object file
ChessEngine/display.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chameleon.dir/build.make CMakeFiles/chameleon.dir/ChessEngine/display.cpp.o
.PHONY : ChessEngine/display.cpp.o

ChessEngine/display.i: ChessEngine/display.cpp.i

.PHONY : ChessEngine/display.i

# target to preprocess a source file
ChessEngine/display.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chameleon.dir/build.make CMakeFiles/chameleon.dir/ChessEngine/display.cpp.i
.PHONY : ChessEngine/display.cpp.i

ChessEngine/display.s: ChessEngine/display.cpp.s

.PHONY : ChessEngine/display.s

# target to generate assembly for a file
ChessEngine/display.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chameleon.dir/build.make CMakeFiles/chameleon.dir/ChessEngine/display.cpp.s
.PHONY : ChessEngine/display.cpp.s

ChessEngine/evaluation.o: ChessEngine/evaluation.cpp.o

.PHONY : ChessEngine/evaluation.o

# target to build an object file
ChessEngine/evaluation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chameleon.dir/build.make CMakeFiles/chameleon.dir/ChessEngine/evaluation.cpp.o
.PHONY : ChessEngine/evaluation.cpp.o

ChessEngine/evaluation.i: ChessEngine/evaluation.cpp.i

.PHONY : ChessEngine/evaluation.i

# target to preprocess a source file
ChessEngine/evaluation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chameleon.dir/build.make CMakeFiles/chameleon.dir/ChessEngine/evaluation.cpp.i
.PHONY : ChessEngine/evaluation.cpp.i

ChessEngine/evaluation.s: ChessEngine/evaluation.cpp.s

.PHONY : ChessEngine/evaluation.s

# target to generate assembly for a file
ChessEngine/evaluation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chameleon.dir/build.make CMakeFiles/chameleon.dir/ChessEngine/evaluation.cpp.s
.PHONY : ChessEngine/evaluation.cpp.s

ChessEngine/position.o: ChessEngine/position.cpp.o

.PHONY : ChessEngine/position.o

# target to build an object file
ChessEngine/position.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chameleon.dir/build.make CMakeFiles/chameleon.dir/ChessEngine/position.cpp.o
.PHONY : ChessEngine/position.cpp.o

ChessEngine/position.i: ChessEngine/position.cpp.i

.PHONY : ChessEngine/position.i

# target to preprocess a source file
ChessEngine/position.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chameleon.dir/build.make CMakeFiles/chameleon.dir/ChessEngine/position.cpp.i
.PHONY : ChessEngine/position.cpp.i

ChessEngine/position.s: ChessEngine/position.cpp.s

.PHONY : ChessEngine/position.s

# target to generate assembly for a file
ChessEngine/position.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chameleon.dir/build.make CMakeFiles/chameleon.dir/ChessEngine/position.cpp.s
.PHONY : ChessEngine/position.cpp.s

ChessEngine/search.o: ChessEngine/search.cpp.o

.PHONY : ChessEngine/search.o

# target to build an object file
ChessEngine/search.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chameleon.dir/build.make CMakeFiles/chameleon.dir/ChessEngine/search.cpp.o
.PHONY : ChessEngine/search.cpp.o

ChessEngine/search.i: ChessEngine/search.cpp.i

.PHONY : ChessEngine/search.i

# target to preprocess a source file
ChessEngine/search.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chameleon.dir/build.make CMakeFiles/chameleon.dir/ChessEngine/search.cpp.i
.PHONY : ChessEngine/search.cpp.i

ChessEngine/search.s: ChessEngine/search.cpp.s

.PHONY : ChessEngine/search.s

# target to generate assembly for a file
ChessEngine/search.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chameleon.dir/build.make CMakeFiles/chameleon.dir/ChessEngine/search.cpp.s
.PHONY : ChessEngine/search.cpp.s

ChessEngine/uci.o: ChessEngine/uci.cpp.o

.PHONY : ChessEngine/uci.o

# target to build an object file
ChessEngine/uci.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chameleon.dir/build.make CMakeFiles/chameleon.dir/ChessEngine/uci.cpp.o
.PHONY : ChessEngine/uci.cpp.o

ChessEngine/uci.i: ChessEngine/uci.cpp.i

.PHONY : ChessEngine/uci.i

# target to preprocess a source file
ChessEngine/uci.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chameleon.dir/build.make CMakeFiles/chameleon.dir/ChessEngine/uci.cpp.i
.PHONY : ChessEngine/uci.cpp.i

ChessEngine/uci.s: ChessEngine/uci.cpp.s

.PHONY : ChessEngine/uci.s

# target to generate assembly for a file
ChessEngine/uci.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chameleon.dir/build.make CMakeFiles/chameleon.dir/ChessEngine/uci.cpp.s
.PHONY : ChessEngine/uci.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chameleon.dir/build.make CMakeFiles/chameleon.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chameleon.dir/build.make CMakeFiles/chameleon.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chameleon.dir/build.make CMakeFiles/chameleon.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... chameleon"
	@echo "... ChessEngine/debug.o"
	@echo "... ChessEngine/debug.i"
	@echo "... ChessEngine/debug.s"
	@echo "... ChessEngine/display.o"
	@echo "... ChessEngine/display.i"
	@echo "... ChessEngine/display.s"
	@echo "... ChessEngine/evaluation.o"
	@echo "... ChessEngine/evaluation.i"
	@echo "... ChessEngine/evaluation.s"
	@echo "... ChessEngine/position.o"
	@echo "... ChessEngine/position.i"
	@echo "... ChessEngine/position.s"
	@echo "... ChessEngine/search.o"
	@echo "... ChessEngine/search.i"
	@echo "... ChessEngine/search.s"
	@echo "... ChessEngine/uci.o"
	@echo "... ChessEngine/uci.i"
	@echo "... ChessEngine/uci.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

